CREATE TABLE IF NOT EXISTS tb_users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP                               NOT NULL,
    updated_at          TIMESTAMP                               NOT NULL,
    deleted_at          TIMESTAMP,
    deleted             BOOLEAN                                 NOT NULL,
    username            VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    display_name        VARCHAR(255),
    dob                 date,
    account_expired     BOOLEAN                                 NOT NULL,
    account_locked      BOOLEAN                                 NOT NULL,
    credentials_expired BOOLEAN                                 NOT NULL,
    role                VARCHAR(255),
    CONSTRAINT pk_tb_users PRIMARY KEY (id)
);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_email UNIQUE (email);

ALTER TABLE tb_users
    ADD CONSTRAINT uc_tb_users_username UNIQUE (username);

CREATE TABLE IF NOT EXISTS tb_posts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP                               NOT NULL,
    updated_at      TIMESTAMP                               NOT NULL,
    deleted_at      TIMESTAMP,
    deleted         BOOLEAN                                 NOT NULL,
    uuid            UUID                                    NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    content         CLOB                                    NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    author_username VARCHAR(255),
    CONSTRAINT pk_tb_posts PRIMARY KEY (id)
);

ALTER TABLE tb_posts
    ADD CONSTRAINT uc_tb_posts_uuid UNIQUE (uuid);

ALTER TABLE tb_posts
    ADD CONSTRAINT FK_TB_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES tb_users (id);

CREATE TABLE IF NOT EXISTS tb_comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP                               NOT NULL,
    updated_at      TIMESTAMP                               NOT NULL,
    deleted_at      TIMESTAMP,
    deleted         BOOLEAN                                 NOT NULL,
    uuid            UUID                                    NOT NULL,
    content         CLOB                                    NOT NULL,
    blog_post_id    BIGINT                                  NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    author_username VARCHAR(255),
    blog_post_uuid  VARCHAR(255),
    CONSTRAINT pk_tb_comments PRIMARY KEY (id)
);

ALTER TABLE tb_comments
    ADD CONSTRAINT uc_tb_comments_uuid UNIQUE (uuid);

ALTER TABLE tb_comments
    ADD CONSTRAINT FK_TB_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES tb_users (id);

ALTER TABLE tb_comments
    ADD CONSTRAINT FK_TB_COMMENTS_ON_BLOG_POST FOREIGN KEY (blog_post_id) REFERENCES tb_posts (id);
